package com.demo.entities;
// Generated May 5, 2024, 7:24:16 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.*;

/**
 * Keyword generated by hbm2java
 */
@Entity
@Table(name = "keyword", catalog = "vietnamjobs")
public class Keyword implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String name;
	private boolean status;

	public Keyword() {
	}

	public Keyword(Category category, String name, boolean status) {
		this.category = category;
		this.name = name;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
