	package com.demo.entities;
// Generated May 11, 2024, 11:59:49 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;

import jakarta.persistence.*;
/**
 * Postingspayment generated by hbm2java
 */
@Entity
@Table(name = "postingspayment", catalog = "vietnamjobs")
public class Postingspayment implements java.io.Serializable {

	private Integer id;
	private Postings postings;
	private double cost;
	private Date created;
	private int duration;
	private boolean status;

	public Postingspayment() {
	}

	public Postingspayment(Postings postings, double cost, Date created, int duration, boolean status) {
		this.postings = postings;
		this.cost = cost;
		this.created = created;
		this.duration = duration;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "postings_id", nullable = false)
	public Postings getPostings() {
		return this.postings;
	}

	public void setPostings(Postings postings) {
		this.postings = postings;
	}

	@Column(name = "cost", nullable = false, precision = 22, scale = 0)
	public double getCost() {
		return this.cost;
	}

	public void setCost(double cost) {
		this.cost = cost;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	
	@Column(name = "duration", nullable = false)
	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
