package com.demo.entities;
// Generated May 5, 2024, 7:24:16 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * TypeAccount generated by hbm2java
 */
@Entity
@Table(name = "type_account", catalog = "vietnamjobs")
public class TypeAccount implements java.io.Serializable {

	private Integer id;
	private String name;
	private boolean status;
	private Set<Account> accounts = new HashSet<Account>(0);

	public TypeAccount() {
	}

	public TypeAccount(String name, boolean status) {
		this.name = name;
		this.status = status;
	}

	public TypeAccount(String name, boolean status, Set<Account> accounts) {
		this.name = name;
		this.status = status;
		this.accounts = accounts;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeAccount")
	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

}
